version: "3"
services:
    devsrv:
        image: vasiliishvakin/webdevelopment:v1.0
        container_name: ${COMPOSE_PROJECT_NAME}_devsrv
        networks:
            default:
                aliases:
                    - devsrv
                    - php
                    - nginx
                    - node
                    - python
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
            - "0.0.0.0:1025:1025"
            - "0.0.0.0:5173:5173"
            - "0.0.0.0:8025:8025"
            - "0.0.0.0:9000:9000"
            - "0.0.0.0:9001:9001"
        volumes:
            - "../:/workspace"
            # - "./php/conf.d/php.local.ini:/usr/local/etc/php/conf.d/zz-01-default.ini"
            # - "./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
            - "../cache/composer:/root/.cache/composer"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "../data/bash/bash_history_php:/root/.bash_history"
            - "~/.gitignore:/root/.gitignore"
            # - "~/.wakatime.cfg:/root/.wakatime.cfg"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        working_dir: /workspace/app
        environment:
            TZ: Asia/Jerusalem

    mysql:
        image: mariadb:10.6
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        networks:
            default:
                aliases:
                    - mysql
        ports:
            - "0.0.0.0:3306:3306"
        volumes:
            - "../data/mysql:/var/lib/mysql"
            - "./mysql/conf.d:/etc/mysql/conf.d"
            - "../data/dump:/docker-entrypoint-initdb.d"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
            TZ: Asia/Jerusalem
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    default:
        name: ${COMPOSE_PROJECT_NAME}-network
